# Generated by Django 6.1.1 on 2026-09-24 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_platform', '0004_alter_aiinvocationrecord_task_type'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='The raw external questionnaire question, exactly as pasted/typed. Untrusted external content - never system authority (PID §7.1).')),
                ('source_label', models.CharField(blank=True, default='', help_text="Optional short source/context label, e.g. 'Acme supplier questionnaire'.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questionnaire_questions', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_questions', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('interpreted_requirement_summary', models.TextField(blank=True, default='')),
                ('intent_type', models.CharField(choices=[('implementation', 'implementation'), ('policy_requirement', 'policy_requirement'), ('artefact_existence', 'artefact_existence'), ('organisation_fact', 'organisation_fact'), ('certification', 'certification'), ('mixed', 'mixed'), ('unclear', 'unclear')], max_length=32)),
                ('requirement_scope', models.CharField(choices=[('all', 'all'), ('some', 'some'), ('existence', 'existence'), ('not_applicable_test', 'not_applicable_test'), ('unspecified', 'unspecified')], max_length=32)),
                ('selected_keys', models.JSONField(blank=True, default=list, help_text='list[str] - validated questionnaire.catalogue keys.')),
                ('evidence_explicitly_requested', models.BooleanField(default=False)),
                ('outcome', models.CharField(choices=[('SUPPORTED', 'SUPPORTED'), ('CONFIRM', 'CONFIRM'), ('GAP', 'GAP'), ('NOT_APPLICABLE', 'NOT_APPLICABLE')], max_length=16)),
                ('ai_draft_text', models.TextField(blank=True, default='', help_text='The AI-drafted answer, exactly as returned.')),
                ('current_answer_text', models.TextField(blank=True, default='', help_text='Editable answer text. Starts equal to ai_draft_text.')),
                ('review_warnings', models.JSONField(blank=True, default=list, help_text='list[str] - human-readable reasons the outcome is not a clean SUPPORTED.')),
                ('grounding_snapshot', models.JSONField(blank=True, default=dict, help_text='Bounded, immutable-once-accepted snapshot of the facts used (PID §7.3).')),
                ('grounding_snapshot_hash', models.CharField(blank=True, default='', max_length=64)),
                ('interpretation_prompt_version', models.CharField(blank=True, default='', max_length=128)),
                ('drafting_prompt_version', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_questionnaire_responses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questionnaire_responses', to=settings.AUTH_USER_MODEL)),
                ('drafting_invocation_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_platform.aiinvocationrecord')),
                ('interpretation_invocation_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_platform.aiinvocationrecord')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='organisations.organisation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaire.questionnairequestion')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='questionnaire.questionnaireresponse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='questionnairequestion',
            index=models.Index(fields=['organisation', 'created_at'], name='questionnai_organis_0ceb07_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresponse',
            index=models.Index(fields=['organisation', 'question'], name='questionnai_organis_3428f0_idx'),
        ),
    ]
