# Generated by Django 6.1.1 on 2026-09-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='current_answer_text',
            field=models.TextField(blank=True, default='', help_text='Editable answer text. For outcome CONFIRM or SUPPORTED, starts equal to a fixed, application-owned safe sentence (never the raw AI draft) - see questionnaire.services.CONFIRM_APPLICATION_SAFE_ANSWER_TEXT / SUPPORTED_APPLICATION_SAFE_ANSWER_TEXT. For GAP or NOT_APPLICABLE, starts equal to ai_draft_text.'),
        ),
    ]
