# Generated by Django 6.1.1 on 2026-10-10 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisationprofile_has_remote_or_offsite_access_and_more'),
        ('questionnaire', '0002_alter_questionnaireresponse_current_answer_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, help_text='Safe display filename as supplied at upload. Never used to derive the storage path.', max_length=255)),
                ('stored_filename', models.CharField(blank=True, help_text='Opaque, server-generated storage identifier. Never derived from the original filename.', max_length=128)),
                ('detected_content_type', models.CharField(blank=True, help_text='From content-sniffing only (the security gate) - never the client-supplied Content-Type.', max_length=255)),
                ('file_format', models.CharField(blank=True, choices=[('xlsx', 'XLSX')], max_length=16)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('security_gate_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('security_gate_result', models.JSONField(blank=True, default=dict, help_text='Structured rejection reason(s) / structural inspection summary / scanner provenance. Never raw file content (WO-M009A Correction 6/Final Correction B).')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('security_gate_pending', 'Security gate pending'), ('security_gate_rejected', 'Security gate rejected'), ('security_gate_failed', 'Security gate failed'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('extraction_failed', 'Extraction failed')], default='uploaded', max_length=24)),
                ('extraction_summary', models.JSONField(blank=True, help_text='Bounded structured summary (sheets discovered/processed/skipped, question/excluded/failed counts, whether any answer destination was found). Never arbitrary workbook body content (WO-M009A Correction 13).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_imports', to='organisations.organisation')),
                ('supersedes', models.ForeignKey(blank=True, help_text='Set when this import is a re-upload intended to replace a prior one. The prior import and all its questions remain, untouched and inspectable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_imports', to='questionnaire.questionnaireimport')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_questionnaire_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireImportQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_extracted_text', models.TextField(help_text='The literal extracted cell text, always populated regardless of disposition.', max_length=32767)),
                ('source_location', models.JSONField(help_text='Versioned XLSX schema v1 source-location contract (WO-M009A Correction 10).')),
                ('extraction_order', models.PositiveIntegerField(help_text='Preserves original document order.')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('extraction_error', models.TextField(blank=True, default='')),
                ('disposition', models.CharField(choices=[('question', 'Question'), ('heading', 'Heading'), ('instructional_text', 'Instructional text'), ('excluded_duplicate', 'Excluded - duplicate'), ('excluded_ambiguous', 'Excluded - ambiguous'), ('excluded_other', 'Excluded - other')], max_length=24)),
                ('import_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.questionnaireimport')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questionnaire.questionnairequestion')),
            ],
            options={
                'ordering': ['extraction_order'],
            },
        ),
        migrations.AddIndex(
            model_name='questionnaireimport',
            index=models.Index(fields=['organisation', 'uploaded_at'], name='questionnai_organis_2c23a0_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireimport',
            index=models.Index(fields=['organisation', 'status'], name='questionnai_organis_bb2e38_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireimportquestion',
            index=models.Index(fields=['import_record', 'extraction_order'], name='questionnai_import__e1adab_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireimportquestion',
            index=models.Index(fields=['import_record', 'disposition'], name='questionnai_import__eacf31_idx'),
        ),
    ]
