# Generated by Django 6.1.1 on 2026-09-23 05:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_platform', '0001_initial'),
        ('key_assets', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_reference', models.CharField(blank=True, help_text='Raw asset/context reference this risk was generated or recorded against.', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('threat', models.TextField()),
                ('vulnerability', models.TextField(help_text='The vulnerability/exposure this risk is about.')),
                ('impact', models.IntegerField(choices=[(1, '1 - Negligible'), (2, '2 - Minor'), (3, '3 - Moderate'), (4, '4 - Major'), (5, '5 - Severe')], help_text='1 (negligible) to 5 (severe). AI may suggest this; the customer can change it before confirmation.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('likelihood', models.IntegerField(choices=[(1, '1 - Rare'), (2, '2 - Unlikely'), (3, '3 - Possible'), (4, '4 - Likely'), (5, '5 - Almost certain')], help_text='1 (rare) to 5 (almost certain). AI may suggest this; the customer can change it before confirmation.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rationale', models.TextField()),
                ('proposed_treatment', models.TextField(help_text='Proposed next action / treatment. A concise proposal, not a full remediation workflow (PID §4).')),
                ('grounding_refs', models.JSONField(default=list, help_text='List of fact/asset references this risk was grounded in (PID §10).')),
                ('assumptions', models.JSONField(default=list, help_text='List of unresolved assumptions/unknowns (PID §11).')),
                ('source', models.CharField(choices=[('ai', 'AI suggested'), ('manual', 'Manual')], default='manual', max_length=8)),
                ('status', models.CharField(choices=[('draft_ai_suggested', 'AI suggested (draft)'), ('confirmed', 'Customer confirmed'), ('dismissed', 'Dismissed')], default='draft_ai_suggested', max_length=32)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_invocation_record', models.ForeignKey(blank=True, help_text='The AI generation run that produced this risk. Null for a manually-created risk.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_risks', to='ai_platform.aiinvocationrecord')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_risks', to=settings.AUTH_USER_MODEL)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_risks', to=settings.AUTH_USER_MODEL)),
                ('key_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='key_assets.keyasset')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
