# Generated by Django 6.1.1 on 2026-09-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='asset_reference',
        ),
        migrations.AddField(
            model_name='risk',
            name='consequence',
            field=models.TextField(default='', help_text="The consequence type if the risk scenario materialises (PID §0.2 derivation spine) - e.g. 'confidential information disclosure'."),
        ),
        migrations.AddField(
            model_name='risk',
            name='exposure',
            field=models.TextField(default='', help_text="The inherent characteristic of the asset/context that creates the opportunity for a threat event (PID §0.2 derivation spine) - e.g. 'portable / leaves controlled premises' for a laptop. Distinct from `vulnerability`: an exposure alone is not yet exploitable."),
        ),
        migrations.AddField(
            model_name='risk',
            name='scenario_id',
            field=models.CharField(blank=True, default='', help_text="Stable reference to the methodology-catalogue scenario (PID §0.4) that produced this risk. A plain CharField, not a ForeignKey: the catalogue is a Python data module, not a database table (intentional - the catalogue itself is built by a separate, parallel dispatch this schema does not depend on). Blank/nullable for a risk that doesn't (yet) trace to a specific catalogue scenario - but per PID §0.7, in M002 V1 every *persisted* Risk row should in practice always have one. This field is only where that trace lives; it is not itself the enforcement mechanism - that is a later dispatch's service-layer concern.", max_length=100),
        ),
        migrations.AddField(
            model_name='risk',
            name='threat_event',
            field=models.TextField(default='', help_text="The specific event that could act on the exposure (PID §0.2 derivation spine) - e.g. 'loss or theft'. See this file's module docstring for a note on its relationship to the pre-existing `threat` field."),
        ),
        migrations.AlterField(
            model_name='risk',
            name='vulnerability',
            field=models.TextField(help_text='The vulnerability/control gap that turns `exposure` into something exploitable (PID §0.2 derivation spine) - e.g. the *absence* of full-disk encryption on a portable laptop. Not a synonym for `exposure`: an inherent characteristic (portable) is not itself a vulnerability - the missing/failed control is.'),
        ),
    ]
