# Generated by Django 6.1.1 on 2026-09-27 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable, unique machine identifier. Never renamed once published.', max_length=64, unique=True)),
                ('label', models.CharField(help_text='Customer-facing navigation label.', max_length=128)),
                ('destination_view_name', models.CharField(help_text='A Django named route (as passed to django.urls.reverse()) - never an arbitrary external URL, template fragment or Python import path (PID §4.1).', max_length=255)),
                ('min_package_tier', models.PositiveSmallIntegerField(help_text='Minimum package tier (0-3) required to see/access this area.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('show_in_navigation', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Nullable self-FK for nested menu structure.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='entitlements.productarea')),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FoundationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable, unique machine identifier. Never renamed once published.', max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('methodology_version', models.CharField(default='2026-09-v1', max_length=32)),
                ('requirement_kind', models.CharField(choices=[('BASELINE_CONTROL', 'Baseline control'), ('DERIVED_MILESTONE', 'Derived milestone')], max_length=32)),
                ('source_key', models.SlugField(help_text='A short, stable, self-documenting string a later resolver registry (WI4) dispatches on - never a Python import path or callable reference (PID §10.2).', max_length=64)),
                ('min_package_tier', models.PositiveSmallIntegerField()),
                ('counts_toward_posture', models.BooleanField(default=False)),
                ('counts_toward_completion', models.BooleanField(default=True)),
                ('security_weight', models.PositiveSmallIntegerField(default=0, help_text='5=critical, 3=important, 1=supporting (PID §11.4). Not meaningful for DERIVED_MILESTONE rows.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foundation_requirements', to='entitlements.productarea')),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='productarea',
            constraint=models.CheckConstraint(condition=models.Q(('min_package_tier__gte', 0), ('min_package_tier__lte', 3)), name='productarea_min_package_tier_in_range'),
        ),
        migrations.AddConstraint(
            model_name='productarea',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='productarea_cannot_parent_itself'),
        ),
        migrations.AddConstraint(
            model_name='foundationrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('min_package_tier__gte', 0), ('min_package_tier__lte', 3)), name='foundationrequirement_min_package_tier_in_range'),
        ),
    ]
