# Generated by Django 6.1.1 on 2026-09-23 04:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='What the asset is, in plain language.', max_length=255)),
                ('category', models.CharField(choices=[('people', 'People'), ('endpoint', 'Endpoint'), ('identity_or_productivity', 'Identity / productivity'), ('cloud_service', 'Cloud service'), ('business_application', 'Business application'), ('information', 'Information'), ('network_or_location', 'Network / location'), ('other', 'Other')], help_text='The kind of thing this asset is.', max_length=32)),
                ('description', models.TextField(blank=True, help_text='A short description of the asset. Optional.')),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='How important this asset is to the business.', max_length=16)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='suggested', max_length=16)),
                ('suggestion_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_assets', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
