# Generated by Django 6.1.1 on 2026-09-23 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('key_assets', '0001_initial'),
        ('organisations', '0001_initial'),
        ('risk_register', '0002_remove_risk_asset_reference_risk_consequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text="What needs to be done. Pre-filled from a risk's proposed treatment when created from a risk.")),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('accepted', 'Accepted (risk consciously accepted for now — not the same as done)')], default='open', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('control_key', models.CharField(blank=True, default='', help_text='Optional reference to a security_baseline catalogue control key. A plain CharField, not a ForeignKey - same convention as risk_register.Risk.scenario_id, since the catalogue is versioned Python data (security_baseline/catalogue.py), not a database table.', max_length=64)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_remediation_actions', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_remediation_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_remediation_actions', to=settings.AUTH_USER_MODEL)),
                ('key_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_actions', to='key_assets.keyasset')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_actions', to='organisations.organisation')),
                ('risk', models.ForeignKey(blank=True, help_text='The risk this action addresses, if created from one (PID §13).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_actions', to='risk_register.risk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
