# Generated by Django 6.1.1 on 2026-09-23 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        ('organisations', '0001_initial'),
        ('remediation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='remediation.remediationaction')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_links', to='evidence.evidenceitem')),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_evidence_links', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_evidence_links', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-linked_at'],
                'indexes': [models.Index(fields=['organisation', 'action'], name='remediation_organis_32869f_idx')],
            },
        ),
    ]
