# Generated by Django 6.1.1 on 2026-09-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0002_actionevidencelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('accepted', 'Accepted')], default='open', max_length=16),
        ),
    ]
