# Generated by Django 6.1.1 on 2026-09-23 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('control_answer_changed', 'Control answer changed'), ('evidence_created', 'Evidence created'), ('evidence_linked', 'Evidence linked'), ('evidence_unlinked', 'Evidence unlinked'), ('evidence_superseded', 'Evidence superseded'), ('evidence_withdrawn', 'Evidence withdrawn'), ('action_created', 'Action created'), ('action_status_changed', 'Action status changed'), ('action_evidence_linked', 'Action evidence linked')], max_length=32)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('control_key', models.CharField(blank=True, default='', help_text='The security_baseline catalogue question key this event relates to, if any.', max_length=64)),
                ('related_object_type', models.CharField(blank=True, default='', help_text="A generic, stable label for a related non-control object (e.g. 'evidence_item', 'remediation_action'), for later dispatches' event types. Blank for control_answer_changed.", max_length=64)),
                ('related_object_id', models.CharField(blank=True, default='', help_text="The related object's stable identifier (e.g. its UUID as a string), paired with related_object_type.", max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Small structured, JSON-safe event detail (e.g. previous/new answer, a note_changed boolean). Never the free-text note content itself (PID §12).')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['organisation', '-occurred_at'], name='activity_ac_organis_cda3d4_idx')],
            },
        ),
    ]
