# Generated by Django 6.1.1 on 2026-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('control_answer_changed', 'Control answer changed'), ('evidence_created', 'Evidence created'), ('evidence_linked', 'Evidence linked'), ('evidence_unlinked', 'Evidence unlinked'), ('evidence_superseded', 'Evidence superseded'), ('evidence_withdrawn', 'Evidence withdrawn'), ('action_created', 'Action created'), ('action_status_changed', 'Action status changed'), ('action_evidence_linked', 'Action evidence linked'), ('risk_suggestion_edited', 'Risk suggestion edited'), ('risk_suggestion_dismissed', 'Risk suggestion dismissed')], max_length=32),
        ),
    ]
