# Generated by Django 6.1.1 on 2026-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activityevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('control_answer_changed', 'Control answer changed'), ('evidence_created', 'Evidence created'), ('evidence_linked', 'Evidence linked'), ('evidence_unlinked', 'Evidence unlinked'), ('evidence_superseded', 'Evidence superseded'), ('evidence_withdrawn', 'Evidence withdrawn'), ('action_created', 'Action created'), ('action_status_changed', 'Action status changed'), ('action_evidence_linked', 'Action evidence linked'), ('risk_suggestion_edited', 'Risk suggestion edited'), ('risk_suggestion_dismissed', 'Risk suggestion dismissed'), ('organisation_person_created', 'Organisation person created'), ('governance_role_changed', 'Governance role changed'), ('workplace_created', 'Workplace created'), ('workplace_updated', 'Workplace updated'), ('policy_draft_generated', 'Policy draft generated'), ('policy_draft_edited', 'Policy draft edited'), ('policy_approved', 'Policy approved'), ('policy_superseded', 'Policy superseded'), ('policy_new_draft_created', 'New policy draft created from approved version'), ('question_created', 'Question created'), ('question_interpreted', 'Question interpreted'), ('questionnaire_response_generated', 'Questionnaire response generated'), ('questionnaire_response_edited', 'Questionnaire response edited'), ('questionnaire_response_accepted', 'Questionnaire response accepted'), ('questionnaire_response_superseded', 'Questionnaire response superseded')], max_length=40),
        ),
    ]
