# Generated by Django 6.1.1 on 2026-09-23 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, default='', help_text='Leave blank if not yet confirmed - e.g. immediately after sign-up, before the Account Holder has reviewed their details.', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive people remain visible/assignable-history but are excluded from new role assignment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_people', to='organisations.organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('policy_authoriser', 'Policy authoriser'), ('security_responsible', 'Security responsible person'), ('senior_leadership', 'Senior leadership representative')], max_length=32)),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_role_assignments', to='organisations.organisation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='governance.organisationperson')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.AddConstraint(
            model_name='organisationperson',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('organisation', 'user'), name='unique_linked_user_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='governanceroleassignment',
            constraint=models.UniqueConstraint(fields=('organisation', 'role'), name='unique_active_assignee_per_role'),
        ),
    ]
