# Generated by Django 6.1.1 on 2026-09-23 04:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInvocationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('initial_risk_generation', 'Initial risk generation')], default='initial_risk_generation', max_length=64)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Request/correlation ID for tracing this invocation end to end.', unique=True)),
                ('prompt_version', models.CharField(help_text="Exact prompt/policy version used (PID §9.4), e.g. 'risk_generation_v1'.", max_length=128)),
                ('model_alias', models.CharField(help_text="Logical/governed alias requested for this call, e.g. 'trinity-core'.", max_length=128)),
                ('resolved_model', models.CharField(blank=True, help_text='Model/provider identity the gateway actually resolved to, when available.', max_length=255, null=True)),
                ('input_snapshot_hash', models.CharField(help_text='SHA-256 hex digest of the canonical grounding payload used for this call - not the raw payload (PID §13).', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('candidate_count', models.IntegerField(default=0)),
                ('error_category', models.CharField(blank=True, choices=[('timeout', 'Timeout'), ('connection_error', 'Connection error'), ('auth_error', 'Authentication/authorisation error'), ('rate_limit', 'Rate limited'), ('invalid_response', 'Invalid/unparseable response'), ('unknown_error', 'Unknown error')], max_length=32, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_invocation_records', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
