# Generated by Django 6.1.1 on 2026-09-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinvocationrecord',
            name='additional_observations',
            field=models.JSONField(blank=True, default=list, help_text='M002-3c dispatch (PID §0.7 third bullet): unvalidated, free-text AI practitioner commentary from a risk_interpretation call - a possible additional concern, or a methodology-coverage-gap note - that is NOT attached to any specific candidate/index and must NEVER be persisted as a Risk row or new catalogue truth. Stored here, on the invocation record, rather than as a separate model: it is generation-run metadata/commentary, exactly like prompt_version or candidate_count, not tenant risk-register state - so it belongs with the record of the call that produced it, clearly separate from risk_register.Risk. Always [] for a TASK_INITIAL_RISK_GENERATION record.'),
        ),
        migrations.AlterField(
            model_name='aiinvocationrecord',
            name='task_type',
            field=models.CharField(choices=[('initial_risk_generation', 'Initial risk generation'), ('risk_interpretation', 'Risk interpretation')], default='initial_risk_generation', max_length=64),
        ),
    ]
