# Generated by Django 6.1.1 on 2026-09-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0002_aiinvocationrecord_additional_observations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinvocationrecord',
            name='task_type',
            field=models.CharField(choices=[('initial_risk_generation', 'Initial risk generation'), ('risk_interpretation', 'Risk interpretation'), ('policy_generation', 'Policy generation')], default='initial_risk_generation', max_length=64),
        ),
    ]
