# Generated by Django 6.1.1 on 2026-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0003_alter_aiinvocationrecord_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinvocationrecord',
            name='task_type',
            field=models.CharField(choices=[('initial_risk_generation', 'Initial risk generation'), ('risk_interpretation', 'Risk interpretation'), ('policy_generation', 'Policy generation'), ('questionnaire_interpretation', 'Questionnaire interpretation'), ('questionnaire_answer_drafting', 'Questionnaire answer drafting')], default='initial_risk_generation', max_length=64),
        ),
    ]
