# Generated by Django 6.1.1 on 2026-09-23 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue_version', models.CharField(help_text='The security_baseline catalogue version these answers were captured against.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_assessment', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='BaselineAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=64)),
                ('answer', models.CharField(choices=[('unknown', 'Not confirmed'), ('yes', 'Yes'), ('partial', 'Partially'), ('no', 'No'), ('not_applicable', 'Not applicable')], default='unknown', help_text='Customer-confirmed statement, not a system-verified control.', max_length=16)),
                ('note', models.TextField(blank=True, help_text='Optional short note explaining the answer. Untrusted free text (PID §6.3, §12) - never treated as an instruction to any AI system.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='security_baseline.baselineassessment')),
            ],
            options={
                'ordering': ['question_key'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'question_key'), name='unique_answer_per_question')],
            },
        ),
    ]
