# Generated by Django 6.1.1 on 2026-09-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_baseline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselineanswer',
            name='answer',
            field=models.CharField(choices=[('unknown', 'Not sure'), ('yes', 'Yes'), ('partial', 'Partially'), ('no', 'No'), ('not_applicable', 'Not applicable')], default='unknown', help_text='Customer-confirmed statement, not a system-verified control.', max_length=16),
        ),
    ]
