# Generated by Django 6.1.1 on 2026-10-02 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_baseline', '0002_alter_baselineanswer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSelectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(help_text='Matches BaselineAnswer.question_key for the same (assessment, question).', max_length=64)),
                ('option_code', models.CharField(help_text='The stable option_code the customer selected (security_baseline.structured_catalogue.STRUCTURED_OPTIONS).', max_length=64)),
                ('methodology_version', models.CharField(help_text='The security_baseline.structured_catalogue.FOUNDATIONS_QUESTION_METHODOLOGY_VERSION active when this option_code was recorded.', max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_details', to='security_baseline.baselineassessment')),
            ],
            options={
                'ordering': ['question_key'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'question_key'), name='unique_selection_detail_per_question')],
            },
        ),
    ]
