# Generated by Django 6.1.1 on 2026-09-22 19:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Short name used to identify this organisation when switching context.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('profile_created', 'Profile created'), ('profile_updated', 'Profile updated')], max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_trading_name', models.CharField(help_text="The organisation's legal or trading name.", max_length=255)),
                ('description', models.TextField(blank=True, help_text='A short description of what the organisation does.')),
                ('staff_count', models.IntegerField(blank=True, help_text='Approximate headcount. Leave blank if not yet confirmed.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('working_model', models.CharField(choices=[('unknown', 'Not confirmed'), ('office', 'Office-based'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='unknown', help_text='How staff mainly work.', max_length=16)),
                ('endpoint_management', models.CharField(choices=[('unknown', 'Not confirmed'), ('company_managed', 'Company-managed devices'), ('byod', 'Bring your own device (BYOD)'), ('both', 'Both company-managed and BYOD')], default='unknown', help_text='How staff devices/endpoints are managed.', max_length=32)),
                ('productivity_platform', models.CharField(choices=[('unknown', 'Not confirmed'), ('microsoft_365', 'Microsoft 365'), ('google_workspace', 'Google Workspace'), ('other', 'Other')], default='unknown', help_text='Primary productivity/email platform.', max_length=32)),
                ('primary_cloud_provider', models.CharField(choices=[('unknown', 'Not confirmed'), ('none', 'None'), ('aws', 'Amazon Web Services (AWS)'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud Platform (GCP)'), ('other', 'Other')], default='unknown', help_text='Primary cloud provider, if applicable.', max_length=16)),
                ('develops_hosts_own_software', models.CharField(choices=[('unknown', 'Not confirmed'), ('yes', 'Yes'), ('no', 'No')], default='unknown', help_text='Does the organisation develop or host its own software/service?', max_length=8)),
                ('handles_personal_data', models.CharField(choices=[('unknown', 'Not confirmed'), ('yes', 'Yes'), ('no', 'No')], default='unknown', help_text='Does the organisation handle personal data?', max_length=8)),
                ('handles_confidential_business_data', models.CharField(choices=[('unknown', 'Not confirmed'), ('yes', 'Yes'), ('no', 'No')], default='unknown', help_text='Does the organisation handle customer confidential/sensitive business data?', max_length=8)),
                ('handles_payment_card_data', models.CharField(choices=[('unknown', 'Not confirmed'), ('yes', 'Yes'), ('no', 'No')], default='unknown', help_text='Does the organisation handle payment-card data directly?', max_length=8)),
                ('handles_special_category_data', models.CharField(choices=[('unknown', 'Not confirmed'), ('yes', 'Yes'), ('no', 'No')], default='unknown', help_text='Does the organisation handle special-category/highly sensitive personal data?', max_length=8)),
                ('receives_security_questionnaires', models.CharField(choices=[('unknown', 'Not confirmed'), ('yes', 'Yes'), ('no', 'No')], default='unknown', help_text='Do customers send this organisation security questionnaires?', max_length=8)),
                ('cyber_essentials_status', models.CharField(choices=[('unknown', 'Not confirmed'), ('not_certified', 'Not certified'), ('in_progress', 'In progress'), ('certified', 'Certified')], default='unknown', help_text='Cyber Essentials certification status.', max_length=16)),
                ('iso27001_status', models.CharField(choices=[('unknown', 'Not confirmed'), ('not_certified', 'Not certified'), ('in_progress', 'In progress'), ('certified', 'Certified')], default='unknown', help_text='ISO 27001 certification status.', max_length=16)),
                ('commercial_security_driver', models.TextField(blank=True, help_text='The immediate commercial/security driver, if known (free text, optional).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner')], default='owner', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisations.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'user'), name='unique_membership_per_org_user')],
            },
        ),
    ]
