# Generated by Django 6.1.1 on 2026-10-02 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_backfill_customer_zero_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationprofile',
            name='has_remote_or_offsite_access',
            field=models.CharField(choices=[('unknown', 'Not confirmed'), ('yes', 'Yes'), ('no', 'No')], default='unknown', help_text="Does anyone access business systems or data from outside the organisation's normal workplace(s), even occasionally (e.g. from home, while travelling)?", max_length=8),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='people_with_system_access_count',
            field=models.IntegerField(blank=True, help_text="How many people - including contractors or anyone else, not just staff - have access to the organisation's business systems or accounts. Leave blank if not yet confirmed.", null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='sector',
            field=models.CharField(choices=[('not_sure', 'Not sure yet'), ('professional_consulting', 'Professional or consulting services'), ('retail_ecommerce', 'Retail or e-commerce'), ('financial_accounting', 'Financial or accounting services'), ('healthcare_care', 'Healthcare or care services'), ('technology_software', 'Technology or software'), ('manufacturing_logistics', 'Manufacturing or logistics'), ('construction_trades', 'Construction or trades'), ('education_training', 'Education or training'), ('legal_services', 'Legal services'), ('hospitality', 'Hospitality'), ('other', 'Other / not listed')], default='not_sure', help_text='Which best describes what the organisation does.', max_length=32),
        ),
        migrations.AlterField(
            model_name='organisationprofile',
            name='commercial_security_driver',
            field=models.CharField(choices=[('not_sure', 'Not sure yet'), ('customer_supplier', 'A customer or supplier has asked us to'), ('sensitive_data', 'We handle sensitive or confidential information'), ('certification_contract', 'We need it for a certification or contract'), ('general_risk', 'We want to reduce cyber risk generally')], default='not_sure', help_text='Why the organisation is working on security now.', max_length=32),
        ),
    ]
