# Generated by Django 6.1.1 on 2026-09-23 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_platform', '0003_alter_aiinvocationrecord_task_type'),
        ('governance', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_document', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='1, 2, 3... per document.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('sections', models.JSONField(default=list, help_text="[{'section_key': ..., 'content': ...}, ...]. Mutable while draft; frozen once approved/superseded (see save()).")),
                ('review_warnings', models.JSONField(default=list, help_text="[{'subject': ..., 'detail': ...}, ...]. Mutable while draft; frozen once approved/superseded.")),
                ('generation_source', models.CharField(choices=[('ai', 'AI generated')], default='ai', max_length=16)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_mode', models.CharField(blank=True, choices=[('direct', 'Direct approval by Policy Authoriser'), ('external_recorded', 'External approval recorded by Account Holder')], max_length=20, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('ai_invocation_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_versions', to='ai_platform.aiinvocationrecord')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policy_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policy.policydocument')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_versions', to='organisations.organisation')),
                ('policy_authoriser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_policy_versions', to='governance.organisationperson')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='policy.policyversion')),
            ],
            options={
                'ordering': ['-version_number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'version_number'), name='unique_version_number_per_document')],
            },
        ),
    ]
