# Generated by Django 6.1.1 on 2026-09-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyversion',
            name='generation_source',
            field=models.CharField(choices=[('ai', 'AI generated'), ('manual', 'Manually created (copied from a previous version)')], default='ai', max_length=16),
        ),
    ]
