# Generated by Django 6.1.1 on 2026-10-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_alter_policyversion_generation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyversion',
            name='generation_source',
            field=models.CharField(choices=[('ai', 'AI generated'), ('manual', 'Manually created (copied from a previous version)'), ('deterministic', 'Deterministic (template-based)')], default='ai', max_length=16),
        ),
    ]
