# Generated by Django 6.1.1 on 2026-09-23 12:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Short human label, e.g. 'London Head Office' or 'Home / remote working'.", max_length=255)),
                ('type', models.CharField(choices=[('distributed_home', 'Distributed / home-based'), ('dedicated_office', 'Dedicated office'), ('shared_office', 'Shared office'), ('coworking_space', 'Coworking space'), ('other', 'Other')], max_length=32)),
                ('location_label', models.CharField(blank=True, help_text="Human-level location, e.g. 'Woking, Surrey' or 'London'. Optional.", max_length=255)),
                ('approx_people_count', models.IntegerField(blank=True, help_text='Approximate number of people normally using this workplace. Leave blank if not known.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
                'indexes': [models.Index(fields=['organisation', 'is_active'], name='workplace_w_organis_552cee_idx')],
            },
        ),
    ]
