# Generated by Django 6.1.1 on 2026-09-23 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('file', 'File'), ('external_reference', 'External reference')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_label', models.CharField(blank=True, help_text="Where this evidence came from, e.g. 'Microsoft 365 admin centre export'.", max_length=255)),
                ('observed_at', models.DateField(blank=True, help_text='When this evidence was captured/observed, if known. Leave blank if not known.', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='When this evidence stops being considered current, if known. Leave blank if there is no known expiry - none is invented.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], default='active', max_length=16)),
                ('original_filename', models.CharField(blank=True, help_text='Safe display filename as supplied at upload. Never used to derive the storage path.', max_length=255)),
                ('stored_filename', models.CharField(blank=True, help_text='Opaque, server-generated storage identifier. Never derived from the original filename.', max_length=128)),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('png', 'PNG'), ('jpeg', 'JPEG'), ('text', 'Plain text')], max_length=16)),
                ('byte_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('reference_url', models.URLField(blank=True, help_text='A syntactically valid URL. Infosecurs does not fetch or crawl it.', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='organisations.organisation')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_evidence_items', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_items', to='evidence.evidenceitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='evidence_ev_organis_f76a49_idx')],
            },
        ),
    ]
