# Generated by Django 6.1.1 on 2026-09-23 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_key', models.CharField(help_text='A security_baseline catalogue control key. Plain CharField - the catalogue is Python data, not a database table.', max_length=64)),
                ('relationship', models.CharField(choices=[('supports', 'Supports'), ('contradicts', 'Contradicts'), ('context', 'Context')], max_length=16)),
                ('rationale', models.CharField(blank=True, default='', help_text='Optional short note explaining why this evidence supports/contradicts/contextualises this control.', max_length=500)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_links', to='evidence.evidenceitem')),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_evidence_links', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_evidence_links', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-linked_at'],
                'indexes': [models.Index(fields=['organisation', 'control_key'], name='evidence_co_organis_8e751c_idx')],
                'constraints': [models.UniqueConstraint(fields=('evidence', 'control_key', 'relationship'), name='unique_evidence_control_relationship')],
            },
        ),
    ]
